dependencies:
- name: activiti-cloud-query
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.7.0
  condition: activiti-base.activiti-cloud-query.enabled,activiti-cloud-query.enabled
- name: activiti-cloud-audit
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.7.0
  condition: activiti-base.activiti-cloud-audit.enabled,activiti-cloud-audit.enabled
- alias: rabbitmq
  name: rabbitmq-ha
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.6.2
  condition: activiti-base.rabbitmq.enabled,rabbitmq.enabled
- name: activiti-cloud-demo-ui
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.1.4
  condition: activiti-base.activiti-cloud-demo-ui.enabled,activiti-cloud-demo-ui.enabled
- name: activiti-cloud-events-adapter
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.0.4
  condition: activiti-base.activiti-cloud-events-adapter.enabled,activiti-cloud-events-adapter.enabled
- name: activiti-cloud-notifications-graphql
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.7.0
  condition: activiti-base.activiti-cloud-notifications-graphql.enabled,activiti-cloud-notifications-graphql.enabled
